LR1 init
Sergey-Dvoraninovich/Android pull request #1
Opened 2020-12-01 10:59 UTC by Sergey-Dvoraninovich

2020-12-02 16:57 UTC, gmltA requested changes

2020-12-02 16:57 UTC, gmltA commented on LR1/app/build.gradle
> +        versionName "1.0"
App versioning is not implemented.

2020-12-02 16:57 UTC, gmltA commented on LR1/app/src/free/java/com/example/myapplication/WeightFragment.java
> +            }
Can you extract similar code from observers?

2020-12-02 16:57 UTC, gmltA commented on LR1/app/src/free/java/com/example/myapplication/WeightFragment.java
> +            }
... and from the spinner listeners?

2020-12-02 16:57 UTC, gmltA commented on LR1/app/src/free/java/com/example/myapplication/WeightFragment.java
> +                model_order.select(new_line_value);
All the conversion logic have to be extracted from the fragment (View level) to separate class. ViewModel should be responsible for conversion via this new class. Fragments should only display data from the view model.

2020-12-02 16:57 UTC, gmltA commented on LR1/app/src/main/java/com/example/myapplication/BlankFragment.java
> +public class BlankFragment extends Fragment {
What is this thing for?

2020-12-02 16:57 UTC, gmltA commented on LR1/app/src/main/java/com/example/myapplication/MainActivity.java
> +        Button button_weight = (Button)findViewById(R.id.button_weignt);
You should not access fragment's view from the activity. Move this logic to the fragment. You can still access the same view model from the fragment.

2020-12-02 16:57 UTC, gmltA commented on LR1/app/src/main/java/com/example/myapplication/SaveTopViewModel.java
> +public class SaveTopViewModel extends ViewModel {
You have a separate ViewModel for each value, am I right?

2020-12-04 13:17 UTC, Sergey-Dvoraninovich commented on LR1/app/build.gradle
> +        versionName "1.0"
Добавлено

2020-12-04 13:17 UTC, Sergey-Dvoraninovich commented on LR1/app/src/free/java/com/example/myapplication/WeightFragment.java
> +            }
Изменено

2020-12-04 13:17 UTC, Sergey-Dvoraninovich commented on LR1/app/src/free/java/com/example/myapplication/WeightFragment.java
> +            }
Изменено

2020-12-04 13:18 UTC, Sergey-Dvoraninovich commented on LR1/app/src/free/java/com/example/myapplication/WeightFragment.java
> +                model_order.select(new_line_value);
Изменено

2020-12-04 13:20 UTC, Sergey-Dvoraninovich commented on LR1/app/src/main/java/com/example/myapplication/BlankFragment.java
> +public class BlankFragment extends Fragment {
Не используется в проекте. Удалено в новом коммите

2020-12-04 13:24 UTC, Sergey-Dvoraninovich commented on LR1/app/src/main/java/com/example/myapplication/MainActivity.java
> +        Button button_weight = (Button)findViewById(R.id.button_weignt);
Я не использовал фрагмент в этом активити

2020-12-04 13:25 UTC, Sergey-Dvoraninovich commented on LR1/app/src/main/java/com/example/myapplication/SaveTopViewModel.java
> +public class SaveTopViewModel extends ViewModel {
Раньше было так. Исправлено в новой версии

2020-12-04 16:36 UTC, gmltA approved these changes
Now it's better.

2020-12-23 16:43 UTC, merged