LR2 init
Sergey-Dvoraninovich/Android pull request #2
Opened 2020-12-01 10:59 UTC by Sergey-Dvoraninovich

2020-12-02 17:19 UTC, gmltA requested changes

2020-12-02 17:19 UTC, gmltA commented on LR2/app/src/main/java/com/example/timerapp/ActivitySettings.java
> +                .commit();
Can't you just put this fragment in the layout markup?

2020-12-02 17:19 UTC, gmltA commented on LR2/app/src/main/java/com/example/timerapp/ActivitySettings.java
> +        db.close();
All DB operations should be extracted to the repository class.

2020-12-02 17:19 UTC, gmltA commented on LR2/app/src/main/java/com/example/timerapp/CreateUpdateActivity.java
> +                    v9 = Integer.toString(random.nextInt(256) - 1);
What's that?)

2020-12-04 13:15 UTC, Sergey-Dvoraninovich commented on LR2/app/src/main/java/com/example/timerapp/ActivitySettings.java
> +                .commit();
Изменено

2020-12-04 13:15 UTC, Sergey-Dvoraninovich commented on LR2/app/src/main/java/com/example/timerapp/ActivitySettings.java
> +        db.close();
Изменено

2020-12-04 13:16 UTC, Sergey-Dvoraninovich commented on LR2/app/src/main/java/com/example/timerapp/CreateUpdateActivity.java
> +                    v9 = Integer.toString(random.nextInt(256) - 1);
Добавление рандомного цвета для нового таймера

2020-12-04 16:41 UTC, gmltA approved these changes
Good.

2020-12-23 16:42 UTC, merged